version: 2
jobs:
  
  build:
    docker:
      - image: davidreband/doiwallet-release:latest 
      
    steps:
      
      - run: 
          name: The First step
          command: docker run --env-file ./keystore_files/env_base64.env davidreband/doiwallet-release  
