version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
      - image: davidreband/doiwallet-release:latest 

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install 
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}

      - run: test -d node_modules || npm i

      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: docker run  -e KEYSTORE_BASE64=$KEYSTORE_BASE64   davidreband/doiwallet-release        

      # run tests!
      #- run: npm t || npm t || npm t


