version: 2
jobs:

  build:
    docker:
      - image: davidreband/doiwallet-release:latest 
      
    steps:
      
      - run: docker run --env-file ./keystore_files/env_base64.env davidreband/doiwallet-release  
